CREATE TABLE Shortener (
  idShort INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Users_idUser INTEGER UNSIGNED NULL,
  Url VARCHAR(300) NOT NULL,
  Short VARCHAR(50) NOT NULL,
  expires TIMESTAMP NULL,
  count INTEGER UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY(idShort),
  INDEX Shortener_FKIndex1(Users_idUser)
);

CREATE TABLE Users (
  idUser INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(120) NOT NULL,
  Login VARCHAR(50) NOT NULL,
  Keyword VARCHAR(55) NOT NULL,
  Token VARCHAR(55) NOT NULL,
  PRIMARY KEY(idUser)
);


